library(shiny)
library(stringr)
library(data.table)
fileconn <- file("data/sampleblog.txt", "rb" )
newblogs <- readLines(fileconn, skipNul = TRUE)
close(fileconn)
fileconn <- file("data/samplenews.txt", "rb")
newnews <- readLines(fileconn, skipNul = TRUE)
close(fileconn)
fileconn <- file("data/sampletwitter.txt", "rb" )
newtwitter <- readLines(fileconn, skipNul = TRUE)
close(fileconn)
fileconn <- file("data/ListProfane.txt")
wordlist <- readLines(fileconn)
close(fileconn)
listword <- unlist(str_split(wordlist, " "))
newblogs <- iconv(newblogs, from = "UTF-8", to = "latin1", sub = "")
newnews <- iconv(newnews, from = "UTF-8", to = "latin1", sub = "")
newtwitter <- iconv(newtwitter, from = "UTF-8", to = "latin1", sub = "")
newblogs <- tolower(newblogs)
newnews <- tolower(newnews)
newtwitter <- tolower(newtwitter)
blogrv <- rbinom(length(newblogs),1,0.9)
sampleblog <- newblogs[blogrv == 1]
newsrv <- rbinom(length(newnews),1,0.9)
samplenews <- newnews[newsrv == 1]
twitterrv <- rbinom(length(newtwitter),1,0.9)
sampletwitter <- newtwitter[twitterrv == 1]
source("./tokeniser.R")
wordblog <- tokeniser(sampleblog)
wordnews <- tokeniser(samplenews)
wordtwitter <- tokeniser(sampletwitter)
alltxt <- c(wordblog,wordnews,wordtwitter)
qb <- quote(wordblog)
qn <- quote(wordnews)
qt <- quote(wordtwitter)
qa <- quote(alltxt)
db <- deparse(qb)
dn <- deparse(qn)
dt <- deparse(qt)
da <- deparse(qa)
datset <- data.frame("v1" = c("blog", "news", "twitter", "all"), "v2" = c(db,dn,dt,da))
source("./mygram.R")
shinyServer(
  function(input,output){
    rd <-reactive({datset[datset$v1 == input$radio1,]})
    extext <- reactive({levels(rd()$v2)[rd()$v2]})
    txts <- reactive({eval(parse(text = extext()))})
    output$otext1 <- renderText({mygram(txts(),input$itext1, listword)})
             })

